// Literature references with DOI hyperlinks.
// Each reference is identified by a short key used by the UI to render
// hover popups next to formulas, datasets and conservation thresholds.

export const REFS = {
    'vanderlaan-2007': {
        authors: 'Vanderlaan A.S.M., Taggart C.T.',
        year: 2007,
        title: 'Vessel collisions with whales: the probability of lethal injury based on vessel speed',
        journal: 'Marine Mammal Science',
        volume: '23(1)',
        pages: '144-156',
        doi: '10.1111/j.1748-7692.2006.00098.x',
        url: 'https://doi.org/10.1111/j.1748-7692.2006.00098.x',
        note: 'Logistic curve for P(lethal) vs vessel speed in knots. β0 = -4.89, β1 = 0.41. P=0.5 at v=11.8 kn.',
    },
    'conn-2013': {
        authors: 'Conn P.B., Silber G.K.',
        year: 2013,
        title: 'Vessel speed restrictions reduce risk of collision-related mortality for North Atlantic right whales',
        journal: 'Ecosphere',
        volume: '4(4)',
        pages: 'art. 43',
        doi: '10.1890/ES13-00004.1',
        url: 'https://doi.org/10.1890/ES13-00004.1',
        note: 'Bayesian re-fit of the lethality-vs-speed curve. P(mortality) ≈ 0.21 at 10 kn, 0.50 at 15 kn.',
    },
    'laist-2001': {
        authors: 'Laist D.W., Knowlton A.R., Mead J.G., Collet A.S., Podesta M.',
        year: 2001,
        title: 'Collisions between ships and whales',
        journal: 'Marine Mammal Science',
        volume: '17(1)',
        pages: '35-75',
        doi: '10.1111/j.1748-7692.2001.tb00980.x',
        url: 'https://doi.org/10.1111/j.1748-7692.2001.tb00980.x',
        note: 'Foundational ship-strike record table. Most lethal injuries occur at vessel speeds ≥ 14 knots.',
    },
    'rockwood-2017': {
        authors: 'Rockwood R.C., Calambokidis J., Jahncke J.',
        year: 2017,
        title: 'High mortality of blue, humpback and fin whales from modeling of vessel collisions on the U.S. West Coast suggests population impacts and insufficient protection',
        journal: 'PLOS ONE',
        volume: '12(8)',
        pages: 'e0183052',
        doi: '10.1371/journal.pone.0183052',
        url: 'https://doi.org/10.1371/journal.pone.0183052',
        note: 'Encounter-theory mortality model. Per-cell expected strikes integrate whale density, ship density, vessel speed and lethality.',
    },
    'williams-2010': {
        authors: 'Williams R., O’Hara P.',
        year: 2010,
        title: 'Modelling ship strike risk to fin whales, humpback whales and killer whales in British Columbia, Canada',
        journal: 'Journal of Cetacean Research and Management',
        volume: '11(1)',
        pages: '1-8',
        doi: '',
        url: 'https://journal.iwc.int/index.php/jcrm/article/view/624',
        note: 'Spatial co-occurrence risk: R(i,j) = whale_density × ship_density. Map of relative risk hotspots.',
    },
    'redfern-2013': {
        authors: 'Redfern J.V. et al.',
        year: 2013,
        title: 'Assessing the risk of ships striking large whales in marine spatial planning',
        journal: 'Conservation Biology',
        volume: '27(2)',
        pages: '292-302',
        doi: '10.1111/cobi.12029',
        url: 'https://doi.org/10.1111/cobi.12029',
        note: 'Marine spatial planning use case. Integrates whale density along vessel routes.',
    },
    'nisi-2024': {
        authors: 'Nisi A.C. et al.',
        year: 2024,
        title: 'Ship collision risk threatens whales across the world’s oceans',
        journal: 'Science',
        volume: '385',
        pages: '1136-1141',
        doi: '10.1126/science.adp1950',
        url: 'https://doi.org/10.1126/science.adp1950',
        note: 'Global blue, fin, humpback and sperm whale habitat-vs-traffic overlap. Mandatory speed restrictions cover only 0.54 percent of blue whale collision-risk hotspots.',
    },
    'noaa-narw-2020': {
        authors: 'NOAA Fisheries',
        year: 2020,
        title: 'North Atlantic Right Whale Vessel Speed Rule Assessment',
        journal: 'Office of Protected Resources',
        volume: 'Final Report',
        pages: '',
        doi: '',
        url: 'https://www.fisheries.noaa.gov/s3/2021-01/FINAL_NARW_Vessel_Speed_Rule_Report_Jun_2020.pdf',
        note: '10-knot mandatory speed limit in Seasonal Management Areas; 80-90 percent reduction in mortality risk.',
    },
    'imo-mepc-674': {
        authors: 'International Maritime Organization',
        year: 2009,
        title: 'Guidance Document for Minimizing the Risk of Ship Strikes with Cetaceans',
        journal: 'IMO',
        volume: 'MEPC.1/Circ.674',
        pages: '',
        doi: '',
        url: 'https://wwwcdn.imo.org/localresources/en/MediaCentre/HotTopics/Documents/MEPC.1-CIRC.674.pdf',
        note: 'Voluntary guidance: traffic separation schemes, areas to be avoided, seasonal speed reduction, crew training.',
    },
    'iwc-strikes': {
        authors: 'International Whaling Commission',
        year: 2026,
        title: 'Vessel strikes',
        journal: 'IWC Conservation Programme',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://iwc.int/management-and-conservation/vessel-strikes',
        note: 'Global ship strike database including reports from Norwegian waters.',
    },
    'gbif': {
        authors: 'GBIF.org',
        year: 2026,
        title: 'GBIF Occurrence Search for order Cetacea, Norwegian and surrounding waters',
        journal: 'Global Biodiversity Information Facility',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://www.gbif.org/occurrence/search?taxon_key=733',
        note: 'CC BY 4.0 / CC0 / CC BY-NC 4.0 (per contributing dataset). 137,820 records in our bounding box; 10K stratified sample shown here.',
    },
    'artsdatabanken': {
        authors: 'Artsdatabanken',
        year: 2021,
        title: 'Norwegian Red List for Species 2021 - Mammals',
        journal: 'Norwegian Biodiversity Information Centre',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://artsdatabanken.no/lister/rodlisteforarter/2021',
        note: 'National red list. 27 of 71 mammal species are red-listed; cetacean entries concentrated on Arctic and great whales.',
    },
    'iucn-cetaceans': {
        authors: 'IUCN SSC Cetacean Specialist Group',
        year: 2024,
        title: 'Red List Status of Cetaceans',
        journal: 'IUCN',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://iucn-csg.org/red-list-status-of-cetaceans/',
        note: 'Global IUCN Red List assessments for cetaceans, updated periodically.',
    },
    'ospar': {
        authors: 'OSPAR Commission',
        year: 2023,
        title: 'List of Threatened and/or Declining Species and Habitats',
        journal: 'OSPAR Quality Status Report 2023',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://www.ospar.org/work-areas/bdc/species-habitats/list-of-threatened-declining-species-habitats',
        note: 'Four cetaceans listed: bowhead, North Atlantic right whale, blue whale, harbour porpoise.',
    },
    'ascobans': {
        authors: 'ASCOBANS',
        year: 2026,
        title: 'Agreement on the Conservation of Small Cetaceans of the Baltic, North-East Atlantic, Irish and North Seas',
        journal: 'UNEP',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://www.ascobans.org/',
        note: 'Conservation agreement covering all small cetaceans except sperm whale.',
    },
    'nammco': {
        authors: 'NAMMCO',
        year: 2026,
        title: 'Species accounts and management advice',
        journal: 'North Atlantic Marine Mammal Commission',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://nammco.no/',
        note: 'Member states: Norway, Iceland, Greenland, Faroes. Provides species accounts and management advice.',
    },
    'emodnet-ais': {
        authors: 'EMODnet Human Activities',
        year: 2024,
        title: 'Vessel Density Maps',
        journal: 'European Marine Observation and Data Network',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://emodnet.ec.europa.eu/en/human-activities',
        note: '1×1 km grid shipping density (hours/km^2/month), 2017-2024. AIS data via CLS, ORBCOMM and vesseltracker.com.',
    },
    'marine-regions': {
        authors: 'Flanders Marine Institute (VLIZ)',
        year: 2023,
        title: 'Maritime Boundaries Geodatabase, version 12',
        journal: 'Marine Regions',
        volume: '',
        pages: '',
        doi: '10.14284/632',
        url: 'https://www.marineregions.org/',
        note: 'Norwegian EEZ outlines (mainland MRGID 5686, Jan Mayen 8437, Svalbard 33181). CC BY 4.0.',
    },
    'natural-earth': {
        authors: 'Natural Earth',
        year: 2026,
        title: '50m physical vectors - coastline',
        journal: 'Public domain',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://www.naturalearthdata.com/',
        note: 'Public domain coastline data, clipped to Norwegian waters bbox.',
    },
    'nilssen-2021': {
        authors: 'Nilssen K.T. et al.',
        year: 2021,
        title: 'Mass strandings of seven toothed and baleen whale species in Northern Norway, March 2020',
        journal: 'Polar Biology',
        volume: '44',
        pages: '761-769',
        doi: '10.1007/s00300-021-02869-6',
        url: 'https://doi.org/10.1007/s00300-021-02869-6',
        note: 'Discusses anthropogenic stressors including shipping in Norwegian waters.',
    },
    'imr': {
        authors: 'Havforskningsinstituttet (Institute of Marine Research)',
        year: 2026,
        title: 'Cetacean abundance estimates from NILS surveys',
        journal: 'IMR',
        volume: '',
        pages: '',
        doi: '',
        url: 'https://www.hi.no/en/hi/temasider/species',
        note: 'Annual abundance estimates from line-transect surveys.',
    },
};

// Helper used by ui.js to build a small DOM popup with a citation and DOI link.
export function refTagHtml(key, label) {
    const r = REFS[key];
    if (!r) return '';
    const linkLabel = label || `${r.authors.split(',')[0]} ${r.year}`;
    const tip = `${r.authors} (${r.year}). ${r.title}. <i>${r.journal}</i>${r.volume ? ', ' + r.volume : ''}${r.pages ? ', ' + r.pages : ''}.${r.note ? '<br><br>' + r.note : ''}${r.doi ? '<br><br>doi: ' + r.doi : ''}`;
    return `<span class="info-tooltip">
        <a class="ref-tag" href="${r.url}" target="_blank" rel="noopener">${linkLabel}</a>
        <span class="tooltip-content">${tip}<br><br><a href="${r.url}" target="_blank" rel="noopener">Open source</a></span>
    </span>`;
}

// Used by the data sources block in the info modal.
export function sourceCardHtml(key) {
    const r = REFS[key];
    if (!r) return '';
    const cite = `${r.authors} (${r.year}). <b>${r.title}</b>. <i>${r.journal}</i>${r.volume ? ', ' + r.volume : ''}${r.pages ? ', ' + r.pages : ''}.${r.doi ? ' doi: ' + r.doi : ''}`;
    return `<div class="source-card">
        <div class="src-name"><a href="${r.url}" target="_blank" rel="noopener">${r.title}</a></div>
        <div class="src-detail">${cite}${r.note ? '<br>' + r.note : ''}</div>
    </div>`;
}
